version: "3.9"

services:
  mongo_c:
    container_name: mongo_c
    image: mongo
    restart: always
    volumes: 
      - mongo_c:/data/db
    ports: 
      - "2737:27017"

  api:
    container_name: api
    environment:
      - PORT=1331
      - DATABASE_URI=mongodb://mongo_c:27017
      - SECRET_KEY=dB6+/QIb0aDuYa6noIBNLe1DU/j3ZOaLnojYiNq9a4BMDmhgIBoef8tD7HOOcOhlLcs7CR+aT8ul3Cjq2N0Q3hhN4ZL6R0Y3FgPyyYkdaCIikNbYsIBlDpw+cudBVxmj4pcQfnjRxjx1NsUOv6IBduwaml9F0AlqJFpnkS+HCS+4hsVA+jpHazp65kQuMKz2K4OFqiK+c2tJzo/jfq/pux4sQeRx1Lc5oMBa3EVKoSdM83OKwc9JO13sG+y5I/WQ0FvgHTyi2M2YPjM9OqHX/Zi57HfLzhp8Qqnyn2nP9RJjUzI03YSa93P3mqVBrneKRJCSdsJkRMkqJihzwMWV6w==
      - ITERATION_VALUE=0
    restart: always
    build: .
    ports:
      - "90:1331"
    depends_on: 
      - mongo_c

volumes:
  mongo_c: {}